/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ot.miniprojekti;

import java.util.Scanner;
import ot.miniprojekti.logic.BookmarkManager;
import ot.miniprojekti.ui.TextUserInterface;
import ot.miniprojekti.dao.Books;
import java.sql.SQLException;

public class App {
    public static void main(String[] args) throws SQLException {
        Scanner reader = new Scanner(System.in);
        
        BookmarkManager bookmarkManager = new BookmarkManager();
        
        Books books = new Books("books.db");
        
        
        TextUserInterface textUserInterface = new TextUserInterface(bookmarkManager, reader, books);
        textUserInterface.start();
    }
}
