/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ot.miniprojekti;

import java.util.Scanner;
import ot.miniprojekti.ui.TextUserInterface;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        
        Scanner reader = new Scanner(System.in);
        TextUserInterface textUserInterface = new TextUserInterface(reader);
        textUserInterface.start();
    }
}
