/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ot.miniprojekti;

import java.util.Scanner;
import ot.miniprojekti.logic.BookmarkManager;
import ot.miniprojekti.ui.TextUserInterface;
import ot.miniprojekti.dao.Books;
import ot.miniprojekti.dao.Podcasts;
import ot.miniprojekti.dao.Tags;
import java.sql.SQLException;

public class App {
    public static void main(String[] args) throws SQLException {
        Scanner reader = new Scanner(System.in);
        
        BookmarkManager bookmarkManager = new BookmarkManager();
        
        Books books = new Books("books.db");
        Podcasts podcasts = new Podcasts("podcasts.db");
        Tags tags = new Tags("tags.db");
        
        TextUserInterface textUserInterface = new TextUserInterface(bookmarkManager, reader, books, podcasts);
        textUserInterface.start();
    }
}
